### ISSUE TITLE
wallet list throws exception if no wallet created

### ISSUE THREAD

**Issue by StevenTCramer** [tangramproject/Tangram.Bamboo#9]
tangram$ ls

  Commands
    exit                 Exits the wallet
    setnodeendpoint      Set contact endpoint
    vault unseal         Begins the Vault unseal process
    wallet balance       Get current wallet balance
    wallet create        Creates a new wallet
    wallet cypher        Claim payment from redemption Key
    wallet get           Retrieves the contents of a wallet
    wallet key           Creates a new key set
    wallet list          Lists the wallets available
    wallet receive       Receive payment
    wallet transactions  List wallet transactions
    wallet transfer      Transfer funds
tangram$ wallet list
VaultSharp.Core.VaultApiException: {"errors":[]}

   at VaultSharp.Core.Polymath.MakeRequestAsync[TResponse](String resourcePath, HttpMethod httpMethod, Object requestData, IDictionary`2 headers, Boolean rawResponse, Action`1 postResponseAction)
   at VaultSharp.Core.Polymath.MakeVaultApiRequest[TResponse](String resourcePath, HttpMethod httpMethod, Object requestData, Boolean rawResponse, Action`1 postResponseAction, String wrapTimeToLive, Boolean unauthenticated)
   at VaultSharp.V1.SecretsEngines.KeyValue.V1.KeyValueSecretsEngineV1Provider.ReadSecretPathsAsync(String path, String mountPoint, String wrapTimeToLive)
   at TangramCypher.ApplicationLayer.Vault.VaultServiceClient.GetListAsync(String path) in C:\git\github\tangram\Cypher-Fork\ApplicationLayer\Vault\VaultServiceClient.cs:line 193
   at TangramCypher.ApplicationLayer.Wallet.WalletService.WalletList() in C:\git\github\tangram\Cypher-Fork\ApplicationLayer\Wallet\WalletService.cs:line 633
   at TangramCypher.ApplicationLayer.Commands.Wallet.WalletListCommand.Execute() in C:\git\github\tangram\Cypher-Fork\ApplicationLayer\Commands\Wallet\WalletListCommand.cs:line 35
   at TangramCypher.ApplicationLayer.Commands.CommandService.Execute(String[] args) in C:\git\github\tangram\Cypher-Fork\ApplicationLayer\Commands\CommandService.cs:line 126
   at TangramCypher.ApplicationLayer.Commands.CommandService.InteractiveCliLoop() in C:\git\github\tangram\Cypher-Fork\ApplicationLayer\Commands\CommandService.cs:line 168
tangram$

**Comment by meany** [comment]
FWIW, this also occurs at the API endpoint /api/Wallet/list.

I played around a bit with creating a `new List<string>` in `wallets/` for vault with no luck - this looks to be an issue for the core devs to enhance the direction for the user to create their first wallet.
